[package]
name = "mtp-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
colors-transform = "0.2.11"
config = "0.15.19"
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
